/** Static catalog of popular US banks/CUs for search suggestions. Not user data. */

export type PopularBank = {
  /** Stable slug used for dedupe against aliases */
  slug: string
  name: string
  aliases: string[]
  defaultCooldownMonths: number
  notes: string
}

export const POPULAR_BANKS: PopularBank[] = [
  {
    slug: 'chase',
    name: 'Chase',
    aliases: ['jpmorgan chase', 'jp morgan chase', 'chase bank'],
    defaultCooldownMonths: 12,
    notes: 'New checking often ~12 months after close.',
  },
  {
    slug: 'bank-of-america',
    name: 'Bank of America',
    aliases: ['bofa', 'boa', 'b of a', 'bank of america bank'],
    defaultCooldownMonths: 12,
    notes: 'Preferential Rewards / Preferred Rewards can complicate “new” status.',
  },
  {
    slug: 'wells-fargo',
    name: 'Wells Fargo',
    aliases: ['wells', 'wf', 'wells fargo bank'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'capital-one',
    name: 'Capital One',
    aliases: ['capital one 360', '360 checking', 'cap one'],
    defaultCooldownMonths: 12,
    notes: 'Watch product-level vs bank-level new-customer rules.',
  },
  {
    slug: 'citi',
    name: 'Citi',
    aliases: ['citibank', 'citibank na', 'citi bank'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'us-bank',
    name: 'U.S. Bank',
    aliases: ['us bank', 'usb', 'u s bank'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'pnc',
    name: 'PNC',
    aliases: ['pnc bank'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'td-bank',
    name: 'TD Bank',
    aliases: ['td', 'toronto dominion'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'ally',
    name: 'Ally',
    aliases: ['ally bank', 'ally financial'],
    defaultCooldownMonths: 12,
    notes: 'Online only.',
  },
  {
    slug: 'discover',
    name: 'Discover',
    aliases: ['discover bank', 'discover cashback checking'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'sofi',
    name: 'SoFi',
    aliases: ['sofi bank', 'so fi'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'american-express',
    name: 'American Express',
    aliases: ['amex', 'amex checking', 'american express national bank'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'truist',
    name: 'Truist',
    aliases: ['bb&t', 'bbt', 'suntrust', 'truist bank'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'regions',
    name: 'Regions',
    aliases: ['regions bank'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'huntington',
    name: 'Huntington',
    aliases: ['huntington bank'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'fifth-third',
    name: 'Fifth Third',
    aliases: ['53', '5/3', 'fifth third bank'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'keybank',
    name: 'KeyBank',
    aliases: ['key bank', 'keycorp'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'citizens',
    name: 'Citizens',
    aliases: ['citizens bank'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'bmo',
    name: 'BMO',
    aliases: ['bmo harris', 'bank of montreal'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'santander',
    name: 'Santander',
    aliases: ['santander bank'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'navy-federal',
    name: 'Navy Federal',
    aliases: ['nfcu', 'navy federal credit union'],
    defaultCooldownMonths: 12,
    notes: 'Credit union — membership required.',
  },
  {
    slug: 'usaa',
    name: 'USAA',
    aliases: ['usaa bank'],
    defaultCooldownMonths: 12,
    notes: 'Eligibility restricted to military community.',
  },
  {
    slug: 'schwab',
    name: 'Charles Schwab',
    aliases: ['schwab bank', 'schwab checking'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'fidelity',
    name: 'Fidelity',
    aliases: ['fidelity cash management', 'fidelity investments'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'marcus',
    name: 'Marcus by Goldman Sachs',
    aliases: ['marcus', 'goldman sachs', 'marcus bank'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'axos',
    name: 'Axos',
    aliases: ['axos bank', 'axos invest'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'synchrony',
    name: 'Synchrony',
    aliases: ['synchrony bank'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'varo',
    name: 'Varo',
    aliases: ['varo bank'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'chime',
    name: 'Chime',
    aliases: ['chime bank'],
    defaultCooldownMonths: 12,
    notes: 'Fintech / partner-bank model — confirm which charter holds the relationship.',
  },
  {
    slug: 'current',
    name: 'Current',
    aliases: ['current bank'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'nbkc',
    name: 'NBKC',
    aliases: ['nbkc bank', 'national bank of kansas city'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'hsbc',
    name: 'HSBC',
    aliases: ['hsbc bank', 'hsbc usa'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'barclays',
    name: 'Barclays',
    aliases: ['barclays bank', 'barclay'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'm&t',
    name: 'M&T Bank',
    aliases: ['mt bank', 'm and t', 'manufacturers and traders'],
    defaultCooldownMonths: 12,
    notes: '',
  },
  {
    slug: 'first-republic',
    name: 'First Republic',
    aliases: ['first republic bank', 'jpmorgan private bank'],
    defaultCooldownMonths: 12,
    notes: 'Relationship may sit under Chase / JPMorgan now.',
  },
]
